project:
  type: website
  output-dir: docs

website:
  title: "CDS Courses"
  navbar:
    background: '#00bc8c'
    left:
      - text: "Courses"
        menu:
          - href: ./courses/network_mapping_101/docs/index.html
            text: 'Network mapping 101'
          - text: 'R programming for Data Science  - beginner'
            url: https://creativedatasolutions.github.io/R_programming_for_DS_beginner/

format:
  html:
    theme: darkly
    css: style.css
    toc: true
    # self-contained: true



